version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: Vaultwarden_PostgreSQLDB_${KUNDENNAME}
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      db_net_vaultwarden: {}
    volumes:
      - /mnt/volumes/vaultwarden_${KUNDENNAME}/vw_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] # <-- HIER IST DIE Ã„NDERUNG!
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  vaultwarden:
    #container_name: vaultwarden
    image: vaultwarden/server:latest
    container_name: vaultwarden_${KUNDENNAME}
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      TEMPLATES_FOLDER: "templates"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      PUSH_INSTALLATION_ID: "${PUSH_INSTALLATION_ID}"
      PUSH_INSTALLATION_KEY: "${PUSH_INSTALLATION_KEY}"
      PUSH_ENABLED: "${PUSH_ENABLED}"
      PUSH_RELAY_URI: "${PUSH_RELAY_URI}"
      PUSH_IDENTITY_URI: "${PUSH_IDENTITY_URI}"
      LOG_FILE: "data/vaultwarden.log"
      TMP_FOLDER: "data/tmp"
      TZ: "Europe/Berlin"
      ENABLE_WEBSOCKET: true
      DOMAIN: "${DOMAIN_VAULTWARDEN}"
    networks:
      db_net_vaultwarden: {}
      nginx-proxy-network:
    volumes:
      - /mnt/volumes/vaultwarden_${KUNDENNAME}/vw_data:/data
      - /mnt/volumes/vaultwarden_${KUNDENNAME}/vw_templates:/templates      
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

networks:
  db_net_vaultwarden":
    driver: bridge
  nginx-proxy-network:
    external: true

