version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      db_net: {}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  vaultwarden:
    #container_name: vaultwarden
    image: vaultwarden/server:latest
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      PUSH_INSTALLATION_ID: "${PUSH_INSTALLATION_ID}"
      PUSH_INSTALLATION_KEY: "${PUSH_INSTALLATION_KEY}"
      PUSH_ENABLED: "${PUSH_ENABLED}"
      PUSH_RELAY_URI: "${PUSH_RELAY_URI}"
      PUSH_IDENTITY_URI: "${PUSH_IDENTITY_URI}"
      LOG_FILE: "data/vaultwarden.log"
      TMP_FOLDER: "data/tmp"
      ENABLE_WEBSOCKET: true
      DOMAIN: "${DOMAIN_VAULTWARDEN}"
    networks:
      db_net: {}
      nginx-proxy-network:
    volumes:
      - vw_data:/data
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  npm:
    image: jc21/nginx-proxy-manager:latest
    environment:
      NPM_ADMIN_EMAIL: "${NPM_ADMIN_EMAIL}"
      NPM_ADMIN_PASSWORD: "${NPM_ADMIN_PASSWORD}"
    networks:
      - nginx-proxy-network
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      - npm_log:/var/log
    restart: unless-stopped

volumes:
  db_data:
  vw_data:
  npm_data:
  npm_letsencrypt:
  npm_log:

networks:
  db_net:
    driver: bridge
  nginx-proxy-network:
    driver: bridge
