version: "3.8"

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${VMIP}:80:${PORT80}"   # Public HTTP Port
      - "${VMIP}:443:${PORT443}" # Public HTTPS Port
      - "${VMIP}:81:${PORT81}"   # Admin Web Port
    environment:
      TZ: "Europe/Berlin"
      # Optional:
      # DB_SQLITE_FILE: "${DB_SQLITE_FILE}"
      # DISABLE_IPV6: "${DISABLE_IPV6}"
    volumes:
      - /mnt/volumes/nginx-proxy-manager/data:/data
      - /mnt/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
