version: "3.8"

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"   # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81"   # Admin Web Port
    environment:
      TZ: "Europe/Berlin"
      # Optional:
      # DB_SQLITE_FILE: "${DB_SQLITE_FILE}"
      # DISABLE_IPV6: "${DISABLE_IPV6}"
    volumes:
      - /mnt/volumes/nginx-proxy-manager/data:/data
      - /mnt/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    driver: bridge
